system:
  variables:
    ENV_RELATIONSHIPS: "PLATFORM_RELATIONSHIPS"
    ENV_ROUTES: "PLATFORM_ROUTES"
    ENV_VARIABLES: "PLATFORM_VARIABLES"
    ENV_APPLICATION: "PLATFORM_APPLICATION"
    ENV_ENVIRONMENT: "PLATFORM_ENVIRONMENT"
stage:
  global:
    VERBOSE_COMMANDS: "-vvv"
    SKIP_HTML_MINIFICATION: true
    X_FRAME_CONFIGURATION: SAMEORIGIN
  build:
    #QUALITY_PATCHES: #this is where you can add patches if needed. https://experienceleague.adobe.com/en/docs/commerce-operations/tools/quality-patches-tool/usage
    QUALITY_PATCHES:
       - ACP2E-5028
    #   - APSB26-73
    VERBOSE_COMMANDS: "-vvv"
    SKIP_SCD: false
    SCD_STRATEGY: "compact"
  deploy:
    VERBOSE_COMMANDS: "-vvv"
    CLEAN_STATIC_FILES: true
    FORCE_UPDATE_URLS: true
    SKIP_SCD: true
    MYSQL_USE_SLAVE_CONNECTION: false #only works with EE - enable during high traffic events with a db replica in place  or if you are using a highly avalible cluster https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/troubleshooting/database/mysql-high-load-bottleneck-in-magento-commerce-cloud#solution:~:text=down%20performance%20by-,10%2D15%25,-%2C%20which%20is%20one
    DATABASE_CONFIGURATION: #https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/troubleshooting/database/read-replicas-issues-synchronization-mariadb-10-6
      _merge: true
      slave_connection:
        default:
          synchronous_replication: false

    VALKEY_BACKEND: symfony_l2
    USE_LUA: false
    USE_LUA_ON_GC: true
    CACHE_CONFIGURATION:
      _merge: true
      allow_parallel_generation: true
      frontend:
        default:
          id_prefix: 'UPSUN_'
          backend_options:
            cleanup_percentage: 30
            remote_backend: valkey
            remote_backend_options:
              database: 0
              serializer: igbinary
              compression_lib: gzip
              persistent: 1
              persistent_id: magento_l2_default
              timeout: 2.5
              read_timeout: 10
              connect_retries: 3
              compress_data: 0
              preload_keys:
                - 'EAV_ENTITY_TYPES:hash'
                - 'db_is_up_to_date:hash'
                - 'system_default:hash'
                - 'extension_attributes_config:hash'
            local_backend: apcu
            local_backend_options:
              slab_size: 0
        stale_cache_enabled:
          id_prefix: '001_l2_'
          backend: symfony_l2
          backend_options:
            cleanup_percentage: 90
            remote_backend: valkey
            remote_backend_options:
              database: 0
              serializer: igbinary
              compression_lib: gzip
              persistent: 1
              persistent_id: magento_l2_stale
              timeout: 2.5
              read_timeout: 10
              connect_retries: 3
              compress_data: 0
            local_backend: apcu
            local_backend_options:
              slab_size: 0
            use_stale_cache: true
      type:
        default:
          frontend: default
        layout:
          frontend: stale_cache_enabled
        block_html:
          frontend: stale_cache_enabled
        reflection:
          frontend: stale_cache_enabled
        config_integration:
          frontend: stale_cache_enabled
        config_integration_api:
          frontend: stale_cache_enabled
        full_page:
          frontend: stale_cache_enabled
        translate:
          frontend: stale_cache_enabled
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        timeout: 5
        compression_threshold: 2048
        compression_library: gzip
        log_level: 4
        disable_locking: 1
        max_concurrency: 10
        break_after_frontend: 10
        break_after_adminhtml: 30
        first_lifetime: 600
        bot_first_lifetime: 60
        bot_lifetime: 7200
        max_lifetime: 2592000
        min_lifetime: 60
    VALKEY_USE_SLAVE_CONNECTION: false #no replica setup for redis currently.
    CRON_CONSUMERS_RUNNER:
      cron_run: false # no need to run consumers in crons as we have workers
      #max_messages: 250
      #consumers: []
  post-deploy:
    WARM_UP_CONCURRENCY: 1
    WARM_UP_PAGES:
      - "index.php"
