; php.ini

;
; Increase PHP memory limit
;
memory_limit = 1024M

;
; enable resulting html compression
;
zlib.output_compression = on

;
; Increase realpath cache size
;
realpath_cache_size = 10M

;
; Increase realpath cache ttl
;
realpath_cache_ttl = 7200


;
; Multi store support
;

auto_prepend_file = "${PLATFORM_APP_DIR}/magento-vars.php"

;
; Increase max input variables value
;
max_input_vars = 10000

;
; Setup the session garbage collector
;
session.gc_probability = 1

;
; Setup opcache configuration
;

; Enable timestamp validation globally
opcache.validate_timestamps = 1

; Re-validate file modification timestamps every 60 seconds
opcache.revalidate_freq = 60

#opcache.blacklist_filename="${PLATFORM_APP_DIR}/op-exclude.txt" use this if you have issues with maintenance mode being out of sync between nodes.
opcache.max_accelerated_files=16229
opcache.consistency_checks=0

; Below can be increased to 2048 on a larger application
opcache.memory_consumption = 512
opcache.jit_buffer_size=256M
opcache.jit=1255
