db:
    type: mariadb:12.3
    disk: 2500
    configuration:
      #properties:
      #  optimizer_switch: "rowid_filter=off"
      #  optimizer_use_condition_selectivity: 1
      schemas:
        - main
      endpoints:
        write:
          default_schema: main
          privileges:
            main: admin
        read:
          default_schema: main
          privileges:
            main: ro

cache:
    type: valkey:9.0
    configuration:
        maxmemory_policy: allkeys-lru

session:
    type: valkey-persistent:9.0
    disk: 512
    configuration:
        maxmemory_policy: allkeys-lru

indexer:
    type: opensearch:3
    disk: 512
    configuration:
        plugins:
            - analysis-phonetic
            - analysis-icu
queue:
    type: activemq-artemis:2
    disk: 1024
